config/routes.rb
Rails.application.routes.draw do
  resources :campaigns
  resources :profiles
  # resources :compaigns
  get 'users/payment'

  root to: "home#index"
  get "dashboard", to: "dashboard#index"
  get "agents", to: "home#agents"
  devise_for :users

  resources :users do
    get :payment
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  serialize :skills, Array
  serialize :industry_expertise, Array
  serialize :languages, Array

  def get_data
    require 'net/http'
    url = URI.parse('http://www.ilanceit.com/freelancer_profiles.json')
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) {|http|
      http.request(req)
    }
   JSON.parse(res.body)
  end

  def ilance_profiles
    @ilance_profiles ||= get_data
  end

  def freelancers
    users = ilance_profiles.select {|x| x["user"] && x["user"]["first_name"].present? }
    Profile.transaction do 
      users.each do |user|
        profile = Profile.find_or_create_by(full_name: "#{user["user"]["first_name"]} #{user["user"]["last_name"]}")
        profile.skills = user["skills"]&.split(",")
        profile.title = user["title"]
        profile.full_name = "#{user["user"]["first_name"]} #{user["user"]["last_name"]}"
        profile.bio = user["overview"]
        profile.cost = user["hourly_rate"].to_f
        profile.picture_url = "http://ilanceit.com#{user['avatar']}"
        if profile.save
          puts "user has been created...."
        else
          puts "error...."
        end
      end
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:full_name, :title, :bio, :country, :cost, :picture_url)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </div>

  <div class="field">
    <%= form.label :picture_url %>
    <%= form.text_field :picture_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_show.html.erb
 <div class="card" style="padding: 20px">
  <img class="rounded mx-auto d-block" width="15%" src="<%= @profile.picture_url %>" alt="Card image" >
  <div class="card-body">
    <h5 class="card-title text-center"><%= @profile.full_name %></h5>
      <h6 class="card-title text-center"> $<%= @profile.cost %>0/hr</h6>
    <h6 class="card-text text-center text-secondary"><%= @profile.title %></h6>
  </div>
  <p class="card-text mx-auto d-block">
    <a href="#" class="btn btn-primary">Interview</a>
    <a href="#" class="btn btn-outline-primary">Send Offer</a>
  </p>
</div>
<br />
<div class="card">
  <div class="card-header">
    Bio
  </div>
  <div class="card-body">
      <p><%=simple_format @profile.bio %></p>
  </div>
</div>
<br />

<div class="card">
  <div class="card-header">
    Skills
  </div>
  <div class="card-body">
      <p><%= @profile.skills %></p>
  </div>
</div>

<br />
<div class="card">
  <div class="card-header">
    Industry Expertise
  </div>
  <div class="card-body">
      <p><%= @profile.industry_expertise %></p>
  </div>
</div>
<br />

<div class="card">
  <div class="card-header">
    Languages
  </div>
  <div class="card-body">
      <p><%= @profile.languages %></p>
  </div>
</div>

<br />

<div class="card">
  <div class="card-header">
    Availability
  </div>
  <div class="card-body">
      <p></p>
  </div>
</div>
<br />

<div class="card">
  <div class="card-header">
    Work History
  </div>
  <div class="card-body">
      <p></p>
  </div>
</div>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<div class="row">
  <h3 class="">Marketplace</h3>
</div>
<hr />

<% @profiles.each_slice(4) do |profiles| %>
<% next if profiles.size < 4%>
  <div class="card-deck">
    <% profiles.each do |profile| %>
      <div class="card bg-default" >
        <img class="card-img-top " src="<%= profile.picture_url %>" alt="Card image">
        <div class="card-body ">
          <h5 class="card-title text-center"><%= profile.full_name %></h5>
          <h6 class="card-text text-secondary"><%= profile.title %></h6>
          <p class="card-text text-dark" style="font-size: 10pt"><%= truncate(profile.bio, length: 50) %><a href="#" class="">see more</a></p>
          <p class="card-text">
            <%= link_to  "View Profile", profile, remote: true, class:"btn btn-primary btn-sm"%>
            <span class="col-sm-1 "> $<%= profile.cost %>0/hr</span>
          </p>
        </div>
      </div>
    <% end %>
  </div>
  <br />
<% end %>


<!-- The Modal -->
<div class="modal fade" id="myModal">

  <div class="modal-dialog  modal-dialog-scrollable modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">

      <!-- Modal Header modal-dialog-scrollable-->
      <div class="modal-header" style="padding: 0; border:none;">
        <button type="button" class="close"style="margin-right: 0px;"  data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body profile-view">
        <!-- Dynamic user content -->
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.js.erb
$(".modal-body.profile-view").html("<%=j render 'show' %>");
$('#myModal').modal();