config/routes.rb
Rails.application.routes.draw do
  resources :campaigns
  resources :profiles
  # resources :compaigns
  get 'users/payment'

  root to: "home#index"
  get "dashboard", to: "dashboard#index"
  get "agents", to: "home#agents"
  devise_for :users

  resources :users do
    get :payment
  end
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user, optional: true

  has_many :campaigns_users
  has_many :profiles, through: :campaigns_users
  accepts_nested_attributes_for :campaigns_users
  enum status: %i[draft publish]
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      @profiles = Profile.where(id: params["profile_ids"])
      if @campaign.update(campaign_params.merge(user_id: current_user.id))
        @campaign.profiles << @profiles
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:name, :caller_number, :start_date, :status, :user_id)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<h1> <%= action_name.capitalize%> Campaign </h1>
<hr>

<div class="card">
  <h5 class="card-header">Campaign Details</h5>
  <div class="card-body">
    <%= simple_nested_form_for(campaign) do |f| %>
      <%= f.input :name %>
      <%= f.input :caller_number %>
      <%= f.input :start_date, as: :date %>
      <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/campaigns/edit.html.erb
<h1> Add contact to campaign </h1>
<hr>
<%= simple_nested_form_for(@campaign) do |f| %>
  <%= f.input :name %>
  <% Profile.all.each_slice(4) do |profiles| %>
  <% next if profiles.size < 4%>
    <div class="card-deck">
      <% profiles.each do |profile| %>
        <div class="card bg-default" >
          <img class="card-img-top " src="<%= profile.picture_url %>" alt="Card image">
          <div class="card-body ">
            <h5 class="card-title text-center">
              <input type="checkbox" name=profile_ids[] class="form-check-input" value=<%= profile.id %> />
              <%= profile.full_name %>
            </h5>
            <h6 class="card-text text-secondary"><%= profile.title %></h6>
            <p class="card-text text-dark" style="font-size: 10pt"><%= truncate(profile.bio, length: 50) %><a href="#" class="">see more</a></p>
            <p class="card-text">
              <%= link_to  "View Profile", profile, remote: true, class:"btn btn-primary btn-sm"%>
              <span class="col-sm-1 "> $<%= profile.cost %>0/hr</span>
            </p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <br>
  <br>
  <%= f.submit "Add to campaigns", class: 'btn btn-primary' %>

<% end %>

<!-- The Modal -->
<div class="modal fade" id="myModal">

  <div class="modal-dialog  modal-dialog-scrollable modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">

      <!-- Modal Header modal-dialog-scrollable-->
      <div class="modal-header" style="padding: 0; border:none;">
        <button type="button" class="close"style="margin-right: 0px;"  data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body profile-view">
        <!-- Dynamic user content -->
      </div>
    </div>
  </div>
</div>

app/views/campaigns/index.html.erb
<div class="row">
  <h3 class="">Campaigns</h3>
  <span class="col-lg-7 offset-2">
    <%= link_to ' + New Campaign', new_campaign_path, class: "btn btn-primary pull-right" %>
  </span>
</div>
<hr />

<% @campaigns.each do |campaign| %>
  <div class="card">
    <div class="card-body d-flex justify-content-between align-items-center">
       <%= link_to campaign do%>
        <h5 class="mb-1"><%= campaign.name %></h5>
      <% end %>
      <h6 class="mb-2">
        Start Date: <%= campaign.start_date&.to_date %>
        <hr />
        Status: <span class= "badge badge-primary"><%= campaign.status %></span>
      </h6>
      <span class="">
        <%= link_to 'Edit', edit_campaign_path(campaign) %> |
        <%= link_to 'InActive', campaign, method: :delete, data: { confirm: 'Are you sure?' } %>
      </span>
    </div>
  </div>
  <br />
<% end %>

app/views/campaigns/new.html.erb
<%= render 'form', campaign: @campaign %>

app/views/campaigns/show.html.erb
<h5>Name:<%= @campaign.name %> </h5>
  <br>
  <br>
<h5>Selected profiles:<%= @campaign.profiles.size %> </h5>
<hr>

<% @campaign.profiles.each_slice(4) do |profiles| %>
  <% next if profiles.size < 4%>
  <div class="card-deck" style="display:block">
    <% profiles.each do |profile| %>
      <div class="card bg-default" style="width:300px; float: left">
        <img class="card-img-top " src="<%= profile.picture_url %>" alt="Card image">
        <div class="card-body ">
          <h5 class="card-title text-center"><%= profile.full_name %></h5>
          <h6 class="card-text text-secondary"><%= profile.title %></h6>
          <p class="card-text text-dark" style="font-size: 10pt"><%= truncate(profile.bio, length: 50) %><a href="#" class="">see more</a></p>
          <p class="card-text">
            <%= link_to  "View Profile", profile, remote: true, class:"btn btn-primary btn-sm"%>
            <span class="col-sm-1 "> $<%= profile.cost %>0/hr</span>
          </p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>


<!-- The Modal -->
<div class="modal fade" id="myModal">

  <div class="modal-dialog  modal-dialog-scrollable modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">

      <!-- Modal Header modal-dialog-scrollable-->
      <div class="modal-header" style="padding: 0; border:none;">
        <button type="button" class="close"style="margin-right: 0px;"  data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body profile-view">
        <!-- Dynamic user content -->
      </div>
    </div>
  </div>
</div>